version: "3.8"

services:
  app_db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./.env.prod.db
  app_redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
  app_django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    image: app_django:django
    container_name: app_django
    depends_on:
      - app_db
  payment_api:
    build: ./payment_api
    command: uvicorn payment_api.app:app --host 0.0.0.0 --port 8010 --reload
    volumes:
      - .:/usr/src/api/
    ports:
      - "8010:8010"
    image: payment_api:fastAPI
    container_name: payment_api
  app_celery:
    restart: always
    build:
      context: .
    command: celery -A python_django_team17 worker -l DEBUG
    volumes:
      - .:/usr/src/app
    container_name: app_celery
    depends_on:
      - app_redis
      - app_django
volumes:
  postgres_data:
